---
abstract: 'Pretty-print data structure'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Format-Pretty
requires:
  Data::Format::Pretty::Console: 0
  Data::Format::Pretty::HTML: 0
  Data::Format::Pretty::JSON: 0
  Exporter: 0
  Module::Load: 0
  Module::Loaded: 0
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Data-Format-Pretty/
  repository: http://github.com/sharyanto/perl-Data-Format-Pretty
version: 0.01
